jekyll_analytics:
  Matomo:                 # Add, if you want to track with Matomo (former Piwik Analytics)
    url: matomo.opstad.it # Required - url to Matomo installation without trailing /
    siteId: "2"           # Required - replace with your Matomo site id (Write id as string)
